name: BlockHunt
version: 1.0
description: BlockHunt is a Hide N Seek minigame.
author: Colby_Miner

main: io.github.colbyminer.blockhunt.BlockHunt
softdepend: [LibsDisguises, ProtocolLib, Vault]

commands:
   blockhunt:
     description: All Blockhunt functionality is handled with this command.
     usage: /<command> <arguments>
     aliases: bh